meta:
  engine: 4.0.2
  version: 1
  author: HagelzZ
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  zones:
    matrix:
      anchor:
        rotate: -10
      columns:
        outer:
        pinky:
          key.stagger: 2.5
        ring:
          key.stagger: 7
        middle:
          key.stagger: 5
        index:
          key.stagger: -7
        indexfar:
          key.stagger: -2.5
      rows:
        bottom:
        home:
        top:
        number:
        frow:
    thumbrow:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.5ky]
      columns:
        near:
          key.splay: -21
          key.height: cy
          key.width: cx
          key.padding: 18
        home:
          key.origin: [-11.75, -9]
          key.height: cy
          key.width: cx
          key.padding: 18
        far:
          key.origin: [-9.5, -9]
          key.height: cy
          key.width: cx
          key.padding: 18
      rows:
        thumb:
  mirror:
    ref: matrix_index_home
    distance: 100
outlines:
  plate:
    - what: rectangle
      where: true
      size: [cx + px, cy + py]
      fillet: 1.2
    - what: polygon
      points:
        - ref: thumbrow_near_thumb
          shift: [-9.75, -9.75]
        - ref: matrix_index_bottom
          shift: [-10, -8]
        - ref: matrix_indexfar_frow
          shift: [8, 9.5]
        - ref: mirror_matrix_indexfar_frow
          shift: [8, 9.5]
        - ref: mirror_matrix_index_bottom
          shift: [-10, -8]
        - ref: mirror_thumbrow_near_thumb
          shift: [-9.75, -9.75]
        - ref: mirror_thumbrow_far_thumb
          shift: [9.5, -9.75]
        - ref: thumbrow_far_thumb
          shift: [9.5, -9.75]
      fillet: 1.2
      operation: add
pcbs:
  middle:
    outlines:
      main:
        outline: plate
    footprints:
      keyswitches:
        where: true
        what: choc
        params:
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      pro_micro:
        what: pro_micro
        params:
          orientation: down
        where:
          ref: matrix_indexfar_number
          shift: [50, 0, 10]
