points:
  zones:
    matrix:
      anchor:
        rotate: -10
      columns:
        outer:
        pinky:
          key.stagger: 2.5
        ring:
          key.stagger: 7
        middle:
          key.stagger: 5
        index:
          key.stagger: -7
        indexfar:
          key.stagger: -2.5
      rows:
        bottom:
        home:
        top:
        number:
        frow:
    thumbrow:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -25]
      columns:
        near:
          key.splay: -21
          key.height: cy
          key.width: cx
          key.padding: 18
        home:
          key.origin: [-11.75, -9]
          key.height: cy
          key.width: cx
          key.padding: 18
        far:
          key.origin: [-9.5, -9]
          key.height: cy
          key.width: cx
          key.padding: 18
      rows:
        thumb:
  rotate: 0
  mirror:
    ref: matrix_indexfar_home
    distance: 75